### ISSUE TITLE
História: Sugestão de Resultados de Busca

### ISSUE THREAD

**Issue by ra247362** [PenseNisso/PenseNissoApp#18]
**Relacionada ao épico:** #9 

**Como:** Usuário

**Eu gostaria de:** Poder pesquisar empresas sem me preocupar com a grafia dos nomes

**De forma que:** Consiga encontrar as empresas que quero rapidamente e sem ter que escrever seus nomes com total precisão, facilitando o processo.

**Estimativa:** 5

**Real:**

---

**Critérios de Aceitação:**

- Verifique que as empresas sugeridas pela busca correspondem ao menos parcialmente aos termos usados.
- Verifique que termos sem sentido continuam retornando nenhum resultado.

**Comentários:**

-

**Comment by HaylaPBV** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sugestão de Resultados de Busca](https://trello.com/c/HoYfiyhr/4-sugest%C3%A3o-de-resultados-de-busca)

**Comment by ra247362** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sugestão de Resultados de Busca](https://trello.com/c/Y6BuA3Lj/18-sugest%C3%A3o-de-resultados-de-busca)
