### ISSUE TITLE
História: Acessar Denúncias

### ISSUE THREAD

**Issue by pedroCarvalhoCintra** [PenseNisso/PenseNissoApp#27]
**Relacionada ao épico:** #12 

**Como:** Consumidor

**Eu gostaria de:** Acessar denúncias sobre uma empresa

**De forma que:** Possa me informar sobre a procedência de uma empresa

**Estimativa:** 2

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga receber todas as denúncias de uma empresa.
- Verifique que novas denúncias são adicionadas corretamente à página de uma empresa.

**Comentários:**

-

**Comment by Lozavival** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar Denúncias](https://trello.com/c/EvykeCHT/19-acessar-den%C3%BAncias)
