### ISSUE TITLE
História: Acessar Notícias

### ISSUE THREAD

**Issue by pedroCarvalhoCintra** [PenseNisso/PenseNissoApp#28]
**Relacionada ao épico:** #12 

**Como:** Consumidor

**Eu gostaria de:** Acessar notícias sobre uma empresa

**De forma que:** Possa me informar sobre a procedência de uma empresa

**Estimativa:** 2

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga receber todas as notícias de uma empresa.
- Verifique que novas notícias são adicionadas corretamente à página de uma empresa.

**Comentários:**

-

**Comment by Lozavival** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar Notícias](https://trello.com/c/USYEIKQ1/20-acessar-not%C3%ADcias)
