### ISSUE TITLE
História: Acessar Processos

### ISSUE THREAD

**Issue by pedroCarvalhoCintra** [PenseNisso/PenseNissoApp#29]
**Relacionada ao épico:** #12 

**Como:** Consumidor

**Eu gostaria de:** Acessar processos sobre uma empresa

**De forma que:** Possa me informar sobre a procedência de uma empresa
 
**Estimativa:** 2

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga receber todas os processos de uma empresa.
- Verifique que novos processos são adicionados corretamente à página de uma empresa.

**Comentários:**

-

**Comment by Lozavival** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar Processos](https://trello.com/c/1CjbbBHO/22-acessar-processos)
