### ISSUE TITLE
História: Adicionar Empresas ao Comparador

### ISSUE THREAD

**Issue by pedroCarvalhoCintra** [PenseNisso/PenseNissoApp#30]
**Relacionada ao épico:** #13 

**Como:** Consumidor

**Eu gostaria de:** Comparar a nota e as práticas trabalhistas e ambientais de empresas

**De forma que:** Possa saber se o produto ou serviço que desejo adquirir é proveniente de uma empresa ética

**Estimativa:** 4

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga utilizar o sistema de busca e filtro para buscar as empresas que deseja adicionar ao comparador.
- Verifique que as empresas adicionadas apresentam nota e principais denúncias e/ou processos.

**Comentários:**

-

**Comment by Lozavival** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar Empresas ao Comparador](https://trello.com/c/Th0HSKqB/23-adicionar-empresas-ao-comparador)
