### ISSUE TITLE
História: Adicionar Inúmeras Empresas ao Comparador

### ISSUE THREAD

**Issue by pedroCarvalhoCintra** [PenseNisso/PenseNissoApp#31]
**Relacionada ao épico:** #13 

**Como:** Consumidor

**Eu gostaria de:** Comparar a nota e as práticas trabalhistas e ambientais de um número indefinido de empresas

**De forma que:** Possa saber se o produto ou serviço que desejo adquirir é proveniente de uma empresa ética

**Estimativa:** 2

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga adicionar quantas empresas quiser ao comparador.

**Comentários:**

-

**Comment by Lozavival** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adicionar Inúmeras Empresas ao Comparador](https://trello.com/c/ECFPmBF1/25-adicionar-in%C3%BAmeras-empresas-ao-comparador)
