### ISSUE TITLE
História: Acessar o comparador a partir da página inicial

### ISSUE THREAD

**Issue by pedroCarvalhoCintra** [PenseNisso/PenseNissoApp#32]
**Relacionada ao épico:** #13 

**Como:** Consumidor

**Eu gostaria de:** Acessar o comparador a partir da tela inicial

**De forma que:** Possa fazer a comparação entre determinadas empresas de forma rápida

**Estimativa:** 2

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga acessar o comparador a partir da tela de início da aplicação.

**Comentários:**

-

**Comment by HaylaPBV** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar o comparador a partir da página inicial](https://trello.com/c/tlJRySS7/24-acessar-o-comparador-a-partir-da-p%C3%A1gina-inicial)
