### ISSUE TITLE
História: Acessar o Comparador a partir da Página de uma Empresa

### ISSUE THREAD

**Issue by HaylaPBV** [PenseNisso/PenseNissoApp#33]
**Relacionada ao épico:** #13 

**Como:** Consumidor

**Eu gostaria de:** Acessar o comparador a partir da página de certa empresa

**De forma que:** Possa comparar a instituição em questão com outra(s) de minha escolha

**Estimativa:** 4

**Real:**

---

**Critérios de Aceitação:**

- Verifique que o usuário consiga acessar o comparador a partir da página de uma empresa.
- Verifique que a empresa em questão já esteja adicionada ao comparador.

**Comentários:**

-

**Comment by Lozavival** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar o Comparador a partir da Página de uma Empresa](https://trello.com/c/DDKeIat4/26-acessar-o-comparador-a-partir-da-p%C3%A1gina-de-uma-empresa)

**Comment by HaylaPBV** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Acessar o Comparador a partir da Página de uma Empresa](https://trello.com/c/SabzwW4C/31-acessar-o-comparador-a-partir-da-p%C3%A1gina-de-uma-empresa)
